## installed during container runtime firstboot script:
## apt installs that require user input (interactive):
apt:
  - macchanger
  - msmtp
# Try to avoid any CLI program installs from pip/cargo/cpan/npm or any
# package manager that is not apt or nix. Use them if not available on
# apt or nix only. Or if you need framework/library etc. for development.
go:
  - github.com/raviqqe/muffet/v2@latest
pipx:
  - epy-reader
npm:
  - browser-sync
sdk:
  - 8.0.302-open
# only install bling programs or if you need latest version with nix,
# don't install any language/library/framework with nix. Cause 
# Collaboration gets annoying => keep it to a minimum
nix:
  - vim
  - tmux
  - fzf
  - yq
  - dialog
  - just
  - kind
  - pup
  - html5validator
  - streamlink
  - tldr
  - exercism
  - chezmoi
  - du-dust
  - neo
  - rustdesk
  - act
  - ripgrep-all
  - glow
  - rdrview
  - yt-dlp
  - corectrl
  - delta
  - gocryptfs
