apt:
  - apt-utils
  - man-db
  - bash-completion
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - sudo
  - ssh
  - sshpass
  - sshfs
  - rsync
  - build-essential
  - perl
  - libcurses-perl
  - libncurses5
  - python3
  - python3-dev
  - libssl-dev
  - libffi-dev
cpan:
  - Term::Animation
