apt:
  - build-essential
  - apt-utils
  - libcurses-perl
  - libncurses5
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - man-db
  - perl
  - python
  - sudo
  - ssh
  - sshpass
  - sshfs
  - rsync
  - bash-completion
nix:
  - dialog
  - curl
  - wget
  - vim
  - tmux
  - git
  - gh
  - jq
  - yq
  - w3m
  - shellcheck
  - figlet
  - tree
  - nmap
  - ed
  - bc
  - iputils-ping
  - bind9-dnsutils
  - htop
  - btop
  - net-tools
  - cifs-utils
  - smbclient
  - less
