apt:
  - apt-utils
  - man-db
  - bash-completion
  - curl
  - wget
  - git
  - gh
  - jq
  - w3m
  - shellcheck
  - tree
  - nmap
  - htop
  - btop
  - xclip
  - universal-ctags
  - imagemagick
  - mupdf
  - wofi
  - pandoc
  - asciinema
  - speedtest-cli
  - fd-find
  - ripgrep
  - duf
  - task-spooler
  - aria2
  - netcat
  - age
  - ncal
  - calcurse
  - hyperfine
  - bat
  - weechat
  - macchanger
  - net-tools
  - netdiscover
  - cifs-utils
  - smbclient
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - scdaemon
  - pcscd
  - pcregrep
  - sudo
  - python-is-python3
  - ssh
  - sshpass
  - sshfs
  - rsync
  - build-essential
  - coreutils
  - perl
  - libcurses-perl
  - libncurses5
  - python3
  - python3-dev
  - python3-pip
  - libssl-dev
  - libffi-dev
  - golang
  - neomutt
  - isync
  - msmtp
  - abook
  - notmuch
  - urlview
  - feh
  - newsboat
  - urlscan
  - mpd
  - ncmpcpp
cpan:
  - Term::Animation
go:
  - github.com/raviqqe/muffet/v2@latest
pipx:
  - epy-reader
nix:
  - fzf
  - vim
  - tmux
  - yq
  - dialog
  - just
  - kind
  - pup
  - html5validator
  - streamlink
  - tldr
  - nodejs
  - deno
  - nodePackages.browser-sync
  - exercism
  - chezmoi
  - du-dust
  - neo
  - rustdesk
  - act
  - ripgrep-all
  - glow
  - rdrview
  - yt-dlp
  - corectrl
  - delta
  - gocryptfs
