apt:
  - build-essential
  - apt-utils
  - libcurses-perl
  - libncurses5
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - man-db
  - perl
  - python
  - sudo
  - ssh
  - sshpass
  - sshfs
  - rsync
  - bash-completion
cpan:
  - Term::Animation
